### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by OscarGibson** [phpython/phpython#1]
# Call to undefined method lang_python_main::import()
File phpython/lang/python/python.main.php -> class lang_python_main haven't any method import.
This method call from phython/phpython.php -> class phpython -> method import.

## Steps to reproduce:
1. Clone this repository
2. Create two files: test.py and index.php
- test.py:
`print "hello, I'm python"`
- index.php:
`<?php`
`require_once 'phpython/phpython.php';`
`phpython::import('test.py');`
3. Run `php index.php` in console

## Output from console:

PHP Fatal error:  Uncaught Error: Call to undefined method lang_python_main::import() in /Users/Mac/Documents/project/Snappages/phpython/phpython/phpython.php:23
Stack trace:
#0 /Users/Mac/Documents/project/Snappages/phpython/index.php(6): phpython::import('hello.py')
#1 {main}
  thrown in /Users/Mac/Documents/project/Snappages/phpython/phpython/phpython.php on line 23

Fatal error: Uncaught Error: Call to undefined method lang_python_main::import() in /Users/Mac/Documents/project/Snappages/phpython/phpython/phpython.php:23
Stack trace:
#0 /Users/Mac/Documents/project/Snappages/phpython/index.php(6): phpython::import('hello.py')
#1 {main}
  thrown in /Users/Mac/Documents/project/Snappages/phpython/phpython/phpython.php on line 23

**Comment by vyaspranjal33** [comment]
@francescobianco

**Comment by francescobianco** [comment]
@OscarGibson I actually try to reboot this project into PHP7 version, please to be patient for this error.
But if you are interested in collaborating or using this project I can make an effort

**Comment by itzmerohit** [comment]
Hello @francescobianco ,
I really appreciate your project and i'm so excited to used this, but i'm unable to install and use it properly, will you please collaborate the process from Setup to use of Phpython project. Thanking you!
